openapi: 3.0.0
info:
  version: 1.0.0
  title: Partida list
  description: >-
    This is an OpenAPI Specification created by oas-wizard
    (https://github.com/pafmon/oas-wizard)  
  contact:
    name: PabloFM
    email: pablofm@us.es
    url: 'http://www.isa.us.es'
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
paths:
  /hand:
    post:
      description: Evaluates a set of games
      operationId: evaluateGames
      responses:
        '201':
          description: succesfully evaluated
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
      requestBody:
        x-name: hand
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/partida'
        description: Partida to be created
        required: true
  /api/v1/partidas:
    get:
      description: Returns all partidas
      operationId: getPartidas
      responses:
        '200':
          description: Partida List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/partida'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
    post:
      description: Creates a new partida
      operationId: addPartida
      responses:
        '201':
          description: partida created
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
      requestBody:
        x-name: partida
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/partida'
        description: Partida to be created
        required: true
  '/api/v1/partidas/{jugadas}':
    get:
      description: Returns a partida by jugadas
      operationId: findPartidaByjugadas
      parameters:
        - name: jugadas
          in: path
          description: jugadas of partida to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Partida returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/partida'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
    delete:
      description: deletes a single partida based on the jugadas
      operationId: deletePartida
      parameters:
        - name: jugadas
          in: path
          description: ID of partida to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: partida deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
    put:
      description: Update a partida based on its jugadas
      operationId: updatePartida
      parameters:
        - name: jugadas
          in: path
          description: ID of partida to put
          required: true
          schema:
            type: string
      responses:
        '204':
          description: partida updated
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
      requestBody:
        x-name: partida
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/partida'
        description: Partida to be updated
        required: true
components:
  schemas:
    errorModel:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    partida:
      type: object
      properties:
        jugadas:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            required:
              - jugador
              - apuesta
            properties:
              jugador:
                type: string
                minLength: 1
              apuesta:
                type: number
              cartas:
                type: array
                uniqueItems: true
                minItems: 1
                items:
                  required:
                    - valor
                    - palo
                  properties:
                    valor:
                      type: string
                      minLength: 1
                    palo:
                      type: string
                      minLength: 1
        bote:
          type: string
          minLength: 1
      required:
        - jugadas
        - bote
