name: execute-tests
on: [push]
jobs:
  execute-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: cd pokerApi
      - run: ls
      - run: npm install
      - run: ls
      - run: npm install chai --save
      - run: ls
      - run: npm test
